RegisterServerEvent('cmg3_animations:sync')
AddEventHandler('cmg3_animations:sync', function(target, animationLib, animationLib2, animation, animation2, distans, distans2, height,targetSrc,length,spin,controlFlagTarget,animFlagTarget,attachFlag)
       print("got to srv cmg3_animations:sync")
       print("got that fucking attach flag as ".. tostring(attachFlag))
       TriggerClientEvent('cmg_animations:syncTarget', targetSrc, source, animationLib2, animation2, distans, distans2m height, length,spin,controlFlagTarget,animFlagTarget,attachFlag)
       print("triggering to target: "..tostring(targetSrc))
       TriggerClientEvent('cmg3_animations:syncMe', source, animationLib, animation,length,controlFlagSrc,animFlagTarget)
end)

RegisterServerEvent('cmg3_animations:stop')
AddEventHandler('cmg3_animations:stop', function(targetSrc)
       TriggerClientEvent('cmg:animations:cl_stop', targetSrc)
end)